name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_fancy_tree_view: ^1.2.0
  shimmer: ^3.0.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  pdf: ^3.11.3
  excel: ^2.0.4
  share_plus: ^7.2.1
  printing: ^5.14.2
  mobile_scanner: ^5.2.3  # Barcode & QR Code scanner
  barcode_widget: ^2.0.4  # Barcode generation for printing
  image_picker: ^1.0.4  # Image picker for camera & gallery
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Thin.ttf
          weight: 100